### ISSUE TITLE
PLZ als Kriterium für Preis abfragen

### ISSUE THREAD

**Issue by kleinfreund** [digital-bauhaus/Ferienpass-Anmeldung#14]
(siehe Titel)

**Comment by vktrbhm** [comment]
Der Preis einer Veranstalltung variiert je nachdem welche PLZ angegeben wurde. Befindet sich die angegebene PLZ nicht in einer whitelist ändert sich der Preis. 

Entsprechende PLZs werden angefragt und hier mitgeteilt.

**Comment by vktrbhm** [comment]
Postleitzahlen: 99423, 99425, 99427, 99428

**Comment by kleinfreund** [comment]
Für die Grunddaten wurde ein Feld für die Postleitzahl hinzugefügt. Diese kann später benutzt werden, um den korrekten Preis zu bestimmen.

**Comment by kleinfreund** [comment]
Die Postleitzahl wird abgefragt und die Whitelist ist in den Formulardaten untergebracht. Innerhalb der Hauptkomponente `Registration` kann jetzt bei Bedarf ein abgewandelter Preis errechnet werden.
