### ISSUE TITLE
Pflichtfeld: Richtigkeit der Angaben

### ISSUE THREAD

**Issue by vktrbhm** [digital-bauhaus/Ferienpass-Anmeldung#16]
Der Kunde möchte ein zusätzliches Pflichtfeld im Anmeldeboden bei dem die Eltern die Richtigkeit ihrer Angaben mit einem Hacken bestätigen können. Ohne diese Bestätigung sollen die Veranstalltungen nicht gebucht werden können.

- [ ] „Ich bestätige die Richtigkeit meiner Angaben. Wurden wissentlich falsche Angaben gemacht, darf die Organisation das angemeldete Kind von den Angeboten ausschließen.“

**Comment by kleinfreund** [comment]
Erledigt.
