### ISSUE TITLE
Wiedererkennungswert: Logo auf dem Anmeldebogen

### ISSUE THREAD

**Issue by vktrbhm** [digital-bauhaus/Ferienpass-Anmeldung#17]
Das Logo des Ferienpass-Weimar soll in dem Formular eingefügt werden. Eine entsprechende Vektorgrafik wird angefordert.

**Comment by vktrbhm** [comment]
Das Logo findet ihr im slack channel

**Comment by kleinfreund** [comment]
@vktrbhm Ich denke, wir werden die Headergrafik von http://www.ferienpass-weimar.de verwenden, ausschneiden und auf der Seite verwenden. Momentan gibt es lediglich ein Favicon basierend auf der Grafik im Slack-Channel.
