### ISSUE TITLE
Pflichtfelder sollen ersichtlich sein

### ISSUE THREAD

**Issue by vktrbhm** [digital-bauhaus/Ferienpass-Anmeldung#18]
Die eltern sollen bei der Anmeldung sehen können, welche Felder sie ausfüllen müssen um den Bogen abschicken zu können. Eventuell mit einem kleinen Stern an dem entsprechenden Feld.

**Comment by kleinfreund** [comment]
Dazu müssen wir wissen, welche Felder Pflicht und welche nicht Pflicht sind. Das wurde vorerst nach eigenem Ermessen implementiert und muss später vom Kunden validiert werden.
