### ISSUE TITLE
Anmeldebogen (Nutzer)

### ISSUE THREAD

**Issue by vktrbhm** [digital-bauhaus/Ferienpass-Anmeldung#2]
Ich als **Nutzer** möchte meine eigenen Kinder über einen Anmeldebogen zu bestimmten Veranstalltungen anmelden können. 

---

- [x] 1. Grunddaten
- [x] 2. Angebote
- [x] 3. Krankheiten, Allergien
- [x] 4. Behinderung
- [x] 5. Erklärung
- [x] 6. Datenschutzerklärung

**Comment by kleinfreund** [comment]
Der Abschnitt zu den Angaben zu etwaigen Beeinträchtigungen ist ziemlich kompliziert.

Insbesondere weiß ich nichts mit der Tabelle "Zeitlicher Umfang der erforderlichen Betreuung/Begleitung" unter Punkt 4 "Behinderung" anzufangen (siehe PDF Seite 3).

Ansonsten wurde der Original-Anmeldebogen implementiert und ist aus funktionaler Sicht fertig.

**Comment by vktrbhm** [comment]
@kleinfreund erstmal tut mir Leid, dass ich dazu bisher noch kein Feedback gegeben habe. 

Für den ersten Meilenstein reicht die Funktionalität des Anmeldebogens. Die Frage nach der Tabelle leite ich an das Ferienpass Team weiter. Ich denke aber, dass die Tabelle wie folg gemeint ist:

Datum -> Datum der Veranstaltung an dem das Kind die Betreuung benötigt
Angebot -> Das konkrete Angebot
Beginn / Ende der Betreuung -> Zeitangaben
Stundenumfang -> Stundenangaben

Ich weiß nicht ob das schon deine Frage beantwortet. Ich frage die Kunden aber trotzdem was genau mit dieser Tabelle gemeint ist.
