### ISSUE TITLE
Zahlungssystem (Nutzer)

### ISSUE THREAD

**Issue by vktrbhm** [digital-bauhaus/Ferienpass-Anmeldung#5]
Ich als **Nutzer** möchte direkt die Veranstalltung über ein Zahlungssystem bezahlen können.

**Comment by kleinfreund** [comment]
@vktrbhm Ein integriertes Zahlungssystem wird es doch nach dem momentanen Stand nicht geben, korrekt? Wir fordern lediglich in manchen Fällen schon zu einer Überweisung auf.

Kann dieses Issue geschlossen werden?
